apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.26.0
          args:
            - "--config.file=/etc/alertmanager/config/alertmanager.yaml"
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: alertmanager-secret
              mountPath: /etc/alertmanager/secrets
              readOnly: true
            - name: alertmanager-config
              mountPath: /etc/alertmanager/config
              readOnly: true
      volumes:
        - name: alertmanager-secret
          secret:
            secretName: alertmanager-email
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
