serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 10s

    alerting:
      alertmanagers:
        - namespace: monitoring
          name: prometheus-alertmanager
          port: 9093

    scrape_configs:
      # 1️⃣ Kubernetes Pods (auto-discovered)
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(\d+)
            replacement: $1:$2
            target_label: __address__

      # 2️⃣ Java Spring Boot App (Actuator Prometheus endpoint)
      - job_name: 'java-app'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['java-app-service.default.svc.cluster.local:8080']

      # 3️⃣ Node Exporter (EC2 host monitoring)
      - job_name: 'node_exporter'
        static_configs:
          - targets: ['3.84.102.38:9100']

