# Prometheus values.yaml
# Production-optimized config (works fine in Minikube too)
server:
  enabled: true
  replicaCount: 1
  service:
    type: ClusterIP
    port: 9090
  persistentVolume:
    enabled: false   # You can set this to true with PVC in production
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

alertmanager:
  enabled: false

pushgateway:
  enabled: false

serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(\d+)
            replacement: $1:$2
            target_label: __address__

      - job_name: 'java-app'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['java-app-service.default.svc.cluster.local:8080']
