apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: java-app-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-app-deployment
  minReplicaCount: 2
  maxReplicaCount: 30
  triggers:
    - type: cpu
      metadata:
        type: Utilization    # ✅ old syntax
        value: "70"
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local:9090
        metricName: requests_per_second
        query: sum(rate(http_server_requests_seconds_count{app="java-app"}[1m]))
        threshold: "100"
"




