name: Deploy to Amazon ECR (Spring Boot - Java)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-ecr:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_URI: public.ecr.aws/a0l9x4c2/java-boardgame-webapp
      IMAGE_TAG: latest

    permissions:
      contents: read

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Login to Amazon ECR Public
      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      # Step 4: Build Docker image
      - name: Build Docker image
        working-directory: APPLICATION/frontend
        run: |
          docker build -t java-boardgame-webapp:$IMAGE_TAG .

      # Step 5: Tag Docker image for ECR Public
      - name: Tag Docker image
        run: |
          docker tag java-boardgame-webapp:$IMAGE_TAG $ECR_URI:$IMAGE_TAG

      # Step 6: Push Docker image to Amazon ECR Public
      - name: Push Docker image to Amazon ECR Public
        run: |
          docker push $ECR_URI:$IMAGE_TAG

      # ✅ Step 7: Confirmation message
      - name: Deployment summary
        run: |
          echo "✅ Successfully pushed image to Amazon ECR Public"
          echo "📦 Image: $ECR_URI:$IMAGE_TAG"
